name: time_machine
description: Date and time library for Flutter, Web, and Server with support for timezones, calendars, cultures, formatting and parsing.
version: 0.9.16
homepage: https://github.com/Dana-Ferguson/time_machine

# SDK's lower bound must be compatible with the current version pushed with Flutter
# ./flutter --version
environment:
  sdk: ">=2.12.0-0 <3.0.0"

# Verify flutter_test dependency compatibility first before updating any constraints
# https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml
dependencies:
  meta: "^1.3.0"
#  quiver_hashcode: "^1.0.0"
#  collection: "^1.14.10"
  collection: "^1.15.0"
#  resource: "^2.1.6"
#  flutter:
#    sdk: flutter

dev_dependencies:
  test: "^1.16.8"
  matcher: "^0.12.10"
  pedantic: "^1.11.0"
  args: ^2.0.0
  archive: ^3.1.2
  # used for the TzdbCompiler
  http: "^0.13.1"
  path: "^1.8.0"
  xml: "^5.0.2"

# Flutter Testing
#  test: "^0.12.3"
#  matcher: "^0.12.2+1"
#  flutter_test:
#    sdk: flutter
